import sqlite3

conn = sqlite3.connect('db_sales.db')


cursor = conn.cursor()

cursor.execute("""
CREATE TABLE DISCOUNTS (
    DISCOUNT_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    DISCOUNT_VALUE INTEGER NOT NULL
);
""")

cursor.execute("""
CREATE TABLE SALES (
    SALES_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    SALES_ORDER_ID INTEGER NOT NULL,
    SALES_ORDER_ITEM INTEGER NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    SALES_DATE DATE,
    TRANSACTION_VALUE REAL,
    DISCOUNT_ID INTEGER,  
    CONSTRAINT FK_DISCOUNT_ID FOREIGN KEY (DISCOUNT_ID) REFERENCES DISCOUNTS(DISCOUNT_ID)
);
""")

conn.close()